### ISSUE TITLE
Crate fails to compile with rust 1.25.0-nightly

### ISSUE THREAD

**Issue by garrettmaring** [rust-lang/regex#548]
Following the simple steps of adding `regex="1"` to the Cargo.toml and the running `cargo build`, the regex crate fails to compile.

```
   Compiling regex v1.1.0
error[E0433]: failed to resolve. Could not find `arch` in `std`
 --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/avx2.rs:3:10
  |
3 | use std::arch::x86_64::*;
  |          ^^^^ Could not find `arch` in `std`

error[E0433]: failed to resolve. Could not find `arch` in `std`
 --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:3:10
  |
3 | use std::arch::x86_64::*;
  |          ^^^^ Could not find `arch` in `std`

error: cannot find macro `is_x86_feature_detected!` in this scope
  --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/avx2.rs:11:12
   |
11 |         if is_x86_feature_detected!("avx2") {
   |            ^^^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `is_x86_feature_detected!` in this scope
  --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:23:12
   |
23 |         if is_x86_feature_detected!("ssse3") {
   |            ^^^^^^^^^^^^^^^^^^^^^^^

error[E0412]: cannot find type `__m256i` in this scope
  --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/avx2.rs:60:13
   |
60 |     vector: __m256i,
   |             ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_set1_epi8` in this scope
  --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/avx2.rs:67:25
   |
67 |         u8x32 { vector: _mm256_set1_epi8(n as i8) }
   |                         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m256i` in this scope
  --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/avx2.rs:78:55
   |
78 |         let p = slice.as_ptr() as *const u8 as *const __m256i;
   |                                                       ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_loadu_si256` in this scope
  --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/avx2.rs:79:25
   |
79 |         u8x32 { vector: _mm256_loadu_si256(p) }
   |                         ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m256i` in this scope
  --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/avx2.rs:91:55
   |
91 |         let p = slice.as_ptr() as *const u8 as *const __m256i;
   |                                                       ^^^^^^^ not found in this scope
error[E0425]: cannot find function `_mm_shuffle_epi8` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:132:29
    |
132 |             u8x16 { vector: _mm_shuffle_epi8(self.vector, indices.vector) }
    |                             ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_cmpeq_epi8` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:140:25
    |
140 |             let boolv = _mm_cmpeq_epi8(self.vector, other.vector);
    |                         ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_set1_epi8` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:141:24
    |
141 |             let ones = _mm_set1_epi8(0xFF as u8 as i8);
    |                        ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_andnot_si128` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:142:29
    |
142 |             u8x16 { vector: _mm_andnot_si128(boolv, ones) }
    |                             ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_and_si128` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:150:29
    |
150 |             u8x16 { vector: _mm_and_si128(self.vector, other.vector) }
    |                             ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_movemask_epi8` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:158:13
    |
158 |             _mm_movemask_epi8(self.vector) as u32
    |             ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_alignr_epi8` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:166:29
    |
166 |             u8x16 { vector: _mm_alignr_epi8(self.vector, other.vector, 14) }
    |                             ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_alignr_epi8` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:174:29
    |
174 |             u8x16 { vector: _mm_alignr_epi8(self.vector, other.vector, 15) }
    |                             ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_srli_epi16` in this scope
   --> /Users/garrettmaring/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.1.0/src/vector/ssse3.rs:182:29
    |
182 |             u8x16 { vector: _mm_srli_epi16(self.vector, 4) }
    |                             ^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 36 previous errors

error: Could not compile `regex`.

To learn more, run the command again with --verbose.
```

**Comment by BurntSushi** [comment]
Rust nightly is unstable, and this crate (like most crates) is typically only supported on the latest version of Rust nightly. This crate will never support older versions of Rust nightly. Sorry.
