### ISSUE TITLE
Does not compile on 1.39.0

### ISSUE THREAD

**Issue by goffrie** [rust-lang/regex#685]
#673 seems to have caused regex to stop compiling on rust 1.39.0 (and maybe other versions):
```
error[E0658]: `cfg(doctest)` is experimental and subject to change
   --> src/lib.rs:625:7
    |
625 | #[cfg(doctest)]
    |       ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62210

```

It actually _does_ work on the MSRV 1.28.0 though, presumably since the feature hadn't even been conceived yet and so wasn't unstable :p

**Comment by BurntSushi** [comment]
This was hinted at in #684 and...

> It actually does work on the MSRV 1.28.0 though, presumably since the feature hadn't even been conceived yet and so wasn't unstable

This explains why I couldn't reproduce it, since the first thing I did was try to build regex using 1.28.0.

This should be fixed in `regex 1.3.9` on crates.io.

**Comment by goffrie** [comment]
Thanks!
